spring:
  jpa:
    show-sql: false
    # DB 초기화 및 초기화 전략
    generate-ddl: true # DDL 초기화 할 건지 확인
    hibernate:
      ddl-auto: create   # DDL 초기화시 전략
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    display-request-duration: true
    path: /swagger-ui.html
    #    configUrl: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    try-it-out-enabled: true
    #    url: /apidocs/v11
    tagsSorter: alpha
    operationsSorter: alpha
    use-root-path: true
    enabled: true
  pathsToMatch: #list, url 매핑 목록
    - /api/**
  api-docs:
    path: /apidocs/v1 #Json Format url
    enabled: true
  model-converters:
    pageable-converter:
      enabled: true

app:
  token:
    access-secret: abcdefghijklabcdefghijklabcdefghijklabcdefghijkl
    access-expired: 1800
    refresh-secret: abcdefghijklabcdefghijklabcdefghijklabcdefghijkl
    refresh-expired: 604800


# Register P6LogFactory to log JDBC events
decorator.datasource.p6spy.enable-logging: true
