spring:
  jpa:
    show-sql: false
    # DB 초기화 및 초기화 전략
    generate-ddl: true # DDL 초기화 할 건지 확인
    hibernate:
      ddl-auto: create   # DDL 초기화시 전략
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true


# Register P6LogFactory to log JDBC events
decorator.datasource.p6spy.enable-logging: true
